# Crawl4AI MCP server configuration

mcp_servers:
  - id: crawl4ai
    name: Crawl4AI Server
    enabled: true
    transport: websocket
    url: https://crawl4ai.demonsafe.com/mcp/ws
    initialization_delay: 3000  # Wait 3 seconds after connecting before sending requests
    auth_token: null
    tools:
      - md
      - html
      - screenshot
      - pdf
      - execute_js
      - crawl
      - ask
    tags:
      - web
      - search
      - crawl
    description: "Crawl4AI web research tools with WebSocket transport"